# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

#Base settings
encoding: utf-8
 

# Site settings
title: 永无岛
email: algo_lzw@yahoo.com
description: > # this means to ignore newlines until "baseurl:"
  每个人心里都住着一个小孩,时而蓝天白云,时而疏狂骤雨。
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: Juziluo
github_username:  algolzw

# Build settings
markdown: kramdown
